version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  
  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "8080:80"   # So your site opens at localhost:3000
    depends_on:
      - backend     # Only if backend is needed for API


volumes:
  mongo-data:
