version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-net

  backend:
    build: 
      context: ./backend
    container_name: ecommerce-app-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    networks:
      - ecommerce-net

frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  container_name: ecommerce-app-frontend-1
  ports:
    - "8080:80"
  depends_on:
    - backend
  networks:
    - ecommerce-net
  volumes:
    - ./frontend/index.html:/usr/share/nginx/html/index.html
    - ./assets:/usr/share/nginx/html/assets



volumes:
  mongo-data:

networks:
  ecommerce-net:
    driver: bridge
