name: CI/CD - Frontend to ECR and EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # change if needed

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and tag Docker image
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/my-frontend:latest
        docker build -t $IMAGE_URI ./frontend
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Push image to ECR
      run: |
        docker push $IMAGE_URI

    - name: SSH and deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          docker pull $IMAGE_URI
          docker stop frontend || true
          docker rm frontend || true
          docker run -d -p 80:80 --name frontend $IMAGE_URI
